package domain

import "time"

// Frequency defines the recurrence schedule for a fixed rule.
type Frequency string

const (
	FrequencyDaily   Frequency = "daily"
	FrequencyWeekday Frequency = "weekday"
	FrequencyWeekend Frequency = "weekend"
)

// FixedRule invariants:
//   - Amount is always positive; the engine stores the generated transaction as a negative amount (expense)
//   - Frequency must be one of the Frequency constants; enforced by DB CHECK constraint
//   - IsActive == false → rule is soft-deleted; no new transactions will be generated from it
//   - Past transactions generated by this rule are unaffected when the rule is deactivated or its amount changes
type FixedRule struct {
	ID         string    `db:"id"`
	UserID     string    `db:"user_id"`
	Name       string    `db:"name"`
	CategoryID string    `db:"category_id"`
	Amount     int       `db:"amount"`    // always positive (expense magnitude); stored in smallest currency unit (e.g. paise)
	Frequency  Frequency `db:"frequency"`
	IsActive   bool      `db:"is_active"`
	CreatedAt  time.Time `db:"created_at"`
}
